aws:
  region: us-east-2
  access_key_id: (env:AWS_ACCESS_KEY_ID)
  secret_access_key: (env:AWS_SECRET_ACCESS_KEY)

ec2:
  image_id: "ami-0a260d1172ddb23d1"
  instance_profile_arn: "arn:aws:iam::280362093965:instance-profile/ZKP"
  max_running_instances: 3
  instance_type: "t3.xlarge"

s3:
  bucket: "job-dispatcher-testing"

paths:
  repository_path: "/home/ubuntu/rust-bitvmx-zk-proof"
