[package]
name = "bitvmx-job-dispatcher-types"
version = "0.5.1"
edition = "2021"

[dependencies]

serde = { version = "1.0.219", features = ["derive"] }
bitvmx-cpu-definitions = { git = "https://github.com/FairgateLabs/BitVMX-CPU.git", optional = true, tag = "v0.5.11" }
emulator = { git = "https://github.com/FairgateLabs/BitVMX-CPU.git", tag = "v0.5.11" }
serde_json = "1.0.96"
thiserror = "2.0.12"
hex = "0.4"
bitvmx-job-dispatcher = { path = "../dispatcher" }

[features]
prover = []
emulator = ["bitvmx-cpu-definitions"]
