[package]
name = "bitvmx-job-dispatcher-types"
version = "0.0.2"
edition = "2021"

[dependencies]

serde = { version = "1.0.219", features = ["derive"] }
bitvmx-cpu-definitions = { git = "https://github.com/FairgateLabs/BitVMX-CPU.git", branch = "v.0.0.2", optional = true }
emulator = { git = "https://github.com/FairgateLabs/BitVMX-CPU.git", branch = "v.0.0.2" }
serde_json = "1.0.96"
thiserror = "2.0.12"
hex = "0.4"
bitvmx-job-dispatcher = { git = "https://github.com/FairgateLabs/rust-bitvmx-job-dispatcher.git", branch = "v.0.0.2" }

[features]
prover = []
emulator = ["bitvmx-cpu-definitions"]
