[package]
name = "bitvmx-risczero-dispatcher"
version = "0.7.2"
edition = "2021"

[dependencies]
tracing = "0.1.26"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1.0.64"
ctrlc = "3.2.0"
anyhow = "1.0.95"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.11"
bitvmx-broker = { git = "https://github.com/FairgateLabs/rust-bitvmx-broker.git", tag = "v0.7.2" }
zk-result = { git = "https://github.com/FairgateLabs/rust-bitvmx-zk-proof.git", tag = "v0.7.2" }
hex = "0.4"
bitvmx-job-dispatcher-types = { path = "../jobtypes", features = ["prover"] }
bitvmx-job-dispatcher = { path = "../dispatcher" }
clap = { version = "4.5.32", features = ["derive"] }

[dev-dependencies]
config = "0.15.11"
test-helper = { path = "../test-helper" }

[features]
default = []
aws = ["bitvmx-job-dispatcher/aws"]
