[package]
name = "bitvmx-aws-job-dispatcher"
version = "0.5.0"
edition = "2024"

[dependencies]
aws-config = "1.1"
aws-sdk-ec2 = "1.13"
aws-sdk-ssm = "1.13"
aws-sdk-s3 = "1.13"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5", features = ["derive"] }
serde_yaml = "0.9.19"
serde_json = "1.0.95"
serde = { version = "1.0.219", features = ["derive"] }
ctrlc = "3.2.0"
tracing = "0.1.26"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.95"
thiserror = "2.0.11"
zk-result = { git = "https://github.com/FairgateLabs/rust-bitvmx-zk-proof.git", tag = "v0.5.1" }
bitvmx-broker = { git = "https://github.com/FairgateLabs/rust-bitvmx-broker.git", tag = "v0.5.1" }
rust-bitvmx-storage-backend = { git = "https://github.com/FairgateLabs/rust-bitvmx-storage-backend.git", tag = "v0.5.1" }
bitvmx-settings = { git = "https://github.com/FairgateLabs/rust-bitvmx-settings.git", tag = "v0.5.1" }
bitvmx-dispatcher-utils = { path = "../dispatcher-utils" }

[dev-dependencies]
rand = "0.9.1"
