aws:
  region: us-east-2
  access_key_id: (env:AWS_ACCESS_KEY_ID)
  secret_access_key: (env:AWS_SECRET_ACCESS_KEY)

ec2:
  instance_id: "i-01e9e5bdfac733348"

s3:
  bucket: "prueba-zkp2" #TODO: rename

paths:
  repository_path: "/home/ubuntu/rust-bitvmx-zk-proof"
